feat(internal)：为prepare增加对应记录支付复用
meoying/dbproxy pull request #52
Opened 2024-08-05 14:59 UTC by penyz

2024-08-06 00:40 UTC, longyue0521 requested changes

2024-08-06 00:40 UTC, longyue0521 commented on internal/datasource/shardingsource/sharding_datasource.go
> +	return newStmt, nil
1. preparestatment.Stmts 在这里充当了 “缓存” 的角色, 如果delay_preparestatement 只是充当这个角色, 其实可以将其内部的sync.Map直接放入*ShardingDataSource 作为内部变量
2. 更大的问题:
   - “缓存”有增无减, 每调用一次ShardingDataSource.Prepare内部就创建并缓存了一个datasource.Stmt, 什么时候删除呢? 我觉得是被缓存的datasource.Stmt的Close()方法被调用的时候, 也就是说Stmt.Close()需要使用自己记录的信息构造key,然后回调到“删除”缓存的代码
   - “缓存”的复用与用户实际需求不符, 以 `query.Datasource + "." + query.DB + "." + query.Table` 作为缓存key表示同一个datasource上的同一个db上的同一张表只能有一个stmt, 显然是与实际用户需求不符的, 因为前面使用该stmt的人可能关闭了该stmt, 后面人拿到了也没用了 或者前人要执行的Query与后人的不同. 我觉得应该在internal/datasource/internal/statement包中引入DelayPreparedStatement抽象, 其内部字段至少有实际干活的*sql.Stmt, ID(唯一标识), 对“缓存“的引用, 及构造key所需要的其他信息, DelayPreparedStatement要实现datasource.Stmt接口, 在Close()方法中, 先调用实际干活的*sql.Stmt, 然后构造key, 回调删缓存. 具体需求与解决方案,请再次与 @flycash  确认

2024-08-06 00:40 UTC, longyue0521 commented on internal/datasource/single/db.go
> +	return dataStmt, err
有些没看懂 单机版为什么要用delay来“缓存”创建的stmt?

2024-08-07 08:44 UTC, penyz commented on internal/datasource/single/db.go
> +	return dataStmt, err
我觉得stmts和延迟应该分开，无论是单机还是sharding都应该有一个stmts来存放着这些stmt。然后sharding是又延迟来往stmts存放数据

2024-08-07 09:53 UTC, flycash commented on internal/datasource/shardingsource/sharding_datasource.go
> +	return newStmt, nil
你在这个地方误解了一个地方，Stmt 本身是被 Datasource 管理的。也就是说整个结构是：
```go
type Datasource interface {
    // 这边按照道理来说，可以使用 sql，但是如果用 sql 的话，那么就会出现同一个 sql 只能有一个 prepare stmt
    stmts map[stmt_id]Stmt
}
```
是这种状态维护的。而后在 Stmt 里面就是这种 Datasource + DB + Table 唯一决定了。

又或者你么觉得不太能够理解的话，那么就可以用一个装饰器来管理所有的这些 Stmt：
```go
type StmtFacade struct {
     stmts map[stmt_id]Stmt
}
```
它假装成一个是一个 Stmt，而实际上它管着一大批的 Stmt

2024-08-07 09:54 UTC, flycash commented on internal/datasource/single/db.go
> +	return dataStmt, err
@penyz 我的意思是，你在测试 Stmt 的时候可以用 single 的 datasource 来测试，不是说放到这里=。=也不是说 single 用这个实现。

2024-08-07 09:56 UTC, flycash reviewed
sharding_datasource 你暂时先不用改，你就把 delay_preparestatement 写好就可以。怎么用这个 delay preparestmt 后面再说。

2024-08-07 09:56 UTC, flycash commented on internal/datasource/preparestatment/delay_preparestatment.go
> +var Stmts = NewDelayStmt()
这个变量从这里删除。注意一点，就是你的 DelayStmt 只管实现自己的特性。而别人怎么用，存在哪里不是你要管的事情。你可以想到，我可以用包变量，也可以参考 DelayTx 的那种做法，引入一些额外的结构体来维护这个东西。

2024-08-07 10:01 UTC, longyue0521 commented on internal/datasource/single/db.go
> +	return dataStmt, err
1. 单机情况下, 使用preparestatment.Stmts缓存stmt目的是什么? 能举一些使用场景来说明这么做的好处是什么吗?
2. preparestatment.stmts只是变量名, 其具体类型是*DelayStmt, 这也是我问为什么要用delay, 如果你想表示集中缓存可以用StmtCache之类的更具描述性的类型名. 或许你可以说说delay的定义.
3. preparestatment.stmts是一个包变量, 相当于全局变量,不应该在Prepare中直接引用,应该通过NewDB将其注入db中再使用.

2024-08-08 14:24 UTC, flycash commented on internal/datasource/preparestatment/delay_preparestatment.go
> +type DelayStmt struct {
```go
type DelayStmt struct {
   stmts syncx.Map[string, datasource.Stmt]
}
```
然后你就是执行延迟策略，上面这个是针对某个查询的 PrepareStmt。例如说：
```go
SELECT * FROM users where id IN (1, 2,3) => &DelayStmt{}
```

2024-08-08 14:24 UTC, flycash commented on internal/datasource/preparestatment/delay_preparestatment.go
> +type DelayStmt struct {
然后你的 Prepare Execute 方法：
```go
func (s *DelayStmt)Execute() {
     stmt, ok:= s.stmts.Load(key)
     if !ok { 
       // 在 ds 上开启 PrepareStmt
        stmt = s.ds.Prepare()
     }
}
```

2024-08-08 14:24 UTC, flycash commented on internal/datasource/preparestatment/delay_preparestatment.go
> +type DelayStmt struct {
这时候你会发现你需要 ds 来开启，这个 ds 实际上是执行了分库分表之后的目标库的 ds，你在测试的时候，可以用 single 来测试。

2024-08-10 09:01 UTC, closed without merging