feat(internal)：实现延迟prepare
meoying/dbproxy pull request #56
Opened 2024-08-10 09:04 UTC by penyz

- [ ] 改造finder返回数据结构，从TxBeginner调整为Datasource
- [ ] 实现延迟Prepare相关功能

目前shareding的prepare都是只走主库，这部分还没有去调整

2024-08-11 01:03 UTC, longyue0521 requested changes

2024-08-11 01:03 UTC, longyue0521 commented on internal/datasource/shardingsource/sharding_datasource_test.go
> +				resp = append(resp, *val)
这个测试的目的是什么? 验证Prepare是否符合预期, 这里有两层含义:
1. 根据ctx, 创建了指定类型的Stmt
2. 在1的基础上, Stmt是否能正常工作,通过Stmt完成查询, (这个已经完成)

添加验证1, 断言stmt的底层类型是否符合预期

2024-08-11 03:06 UTC, penyz commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
> 我在[上一个PR的留言中的第2点](https://github.com/meoying/dbproxy/pull/52#discussion_r1704756270)已经提到这个问题, 我再举一个实例:
> 
> 对于query1.SQL = "SELECT user_id, order_id FROM orders WHERE user_id = ?", query1.Args = 1 , 数据库中其对应的order_id = 10 对于query2.SQL = "SELECT user_id, order_id FROM orders WHERE order_id = ?", query2.Args = 1, 数据库中其对应的user_id = 100 两者的Datasource,DB, Table均相同
> 
> 先执行`s.Query(ctx, query1)`, 再执`s.Query(ctx, query2)`, 时,能否得到预期的行数据(user_id = 100, order_id = 1)的数据?
> 
> 当前的代码是不能的应为query1和query2生成的key是相同的, 所以执行query2时, 拿到的是执行query1时生成的stmt, 因为两者的args恰好匹配(但是占位符表示的含义不同),所以不会报错, 但是拿到的数据行是 (user_id = 1, order_id = 10)

你说的两种情况是已经在stmtID就已经可以区分了，这里的stmts保存的是在同一个stmtID里根据分库分表分别创建对应的stmt，所以在同一个stmtID里根据Datasource,DB, Table就唯一了。

2024-08-11 05:00 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
你说的stmtID在当前PR中没有任何体现, 请编写单元测试在验证代码正确性的同时展示如何使用这个DelayStmt.

2024-08-11 06:34 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
我觉得可以直接用`query.Datasource + "." + query.DB + "." + query.SQL` 作key , 也不需要在Query加入Table字段, 这样可以复用当前SQL解析过程, 还有就是一个SQL可能是多表查询, query.Table不太好表达这种情况.

2024-08-11 06:42 UTC, longyue0521 requested changes

2024-08-11 06:42 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement.go
> +}
NewDelayStmt时, 应该将ctx保留为preparedCtx, 因为这是用户调用ds.Prepare(ctx, query)时经由s.factory.StmtOf(dsCtx, s.finder)传递下来的. 表示用户在prepare那时那刻用的ctx

2024-08-11 06:42 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement.go
> +}
s.findOrPrepare(ctx, query) 应该改为 s.findOrPrepare(s.preparedCtx, query) 用用户调用prepare时的ctx来查找或创建分库分表的stmt

2024-08-11 06:42 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement.go
> +	return stmt, nil
```go
stmt, err = ds.Prepare(ctx, query)
if err != nil {
    //....
}
s.stmts[key] = stmt
return stmt, nil
```

2024-08-11 15:40 UTC, penyz commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
我觉得是可以的，但SQL的话可能要注意它的长度，和对内存不太友好。

2024-08-12 02:18 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
可以将现在的key进行哈希计算再用base64.RawURLEncoding.EncodeToString, 或者直接base64, 生成具有唯一性、长度固定的字符串作为map的key

2024-08-13 06:56 UTC, penyz commented on internal/datasource/shardingsource/sharding_datasource_test.go
> +				resp = append(resp, *val)
> 这个测试的目的是什么? 验证Prepare是否符合预期, 这里有两层含义:
> 
> 1. 根据ctx, 创建了指定类型的Stmt
> 2. 在1的基础上, Stmt是否能正常工作,通过Stmt完成查询, (这个已经完成)
> 
> 添加验证1, 断言stmt的底层类型是否符合预期, 这个“断言”的方式使用间接的方式来断言 —— 利用精心挑选的测试数据来证明这是一个delay stmt实现, 而不是一个single stmt.

有点不明白？为什么不能直接断言来判断stmt来判断底层类型？你说的间接是说例如我第一次查的数据是在一个datasource，下一次查的是另外的datasource。那是不是delayStmt还要开放一个查询stmts的方法才能去简介判断呢？

2024-08-13 08:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
> 我觉得可以直接用query.Datasource + "." + query.DB + "." + query.SQL 作key , 也不需要在Query加入Table字段, 这样可以复用当前SQL解析过程, 还有就是一个SQL可能是多表查询, query.Table不太好表达这种情况.

这个不需要考虑多个表的情况。因为多个表就意味着是 JOIN 查询。而 JOIN 查询我们面临的就不是这个问题了。因此简单的 datasource + db + table 是最适合的 key 的载体。

后续我们也不会支持 JOIN 查询，因为跨库 JOIN 这个东西从实践上来说就不是一个好东西。

另外，stmt_id 这个不需要管那么快，等下一个合并请求再来管。这个合并请求先解决 delay stmt 这个设计来。下一个合并请求再把 delay 和 query handler 之类的结合在一起。

2024-08-13 08:58 UTC, flycash commented on internal/datasource/shardingsource/sharding_datasource_test.go
> +	testCasesQuery := []struct {
这个测试用例要至少一下场景：
- 目标查询在 stmts 里面没有 PrepreStmt，所以你新建了一个;
- 目标查询在 stmts 里面有 PrepareStmt，所以使用的是老的 PrepareStmt
- 而后要考虑 datasource 不同、db 不同或者 table 不同导致新建，确保我们的 delay 策略在分 datasource 分库分表之下都正常运作。

2024-08-13 08:58 UTC, flycash commented on internal/datasource/shardingsource/sharding_datasource_test.go
> +	testCasesQuery := []struct {
而后新开一个测试，里面用事务来测试，也就是确保事务里面使用 delay_stmt 是可以的。

我的建议是把这个测试挪过去 statement 的 delay_statement_test 里面，而后写一个专门的测试的 datasource.Datasource，又或者用 mockgen 工具来生成 datasource 里面全部接口的对应的 mock 实现来测试。

2024-08-13 08:58 UTC, flycash commented on internal/datasource/internal/statement/type.go
> +type StmtFactory interface {
这边先不要引入这些复杂的设计。

暂时只留一个 Prepare 方法：
```go

func Prepare(ctx context.Contex, s datasource.Datasource, q Query) {

}
```
这个方法固定返回 DelayStmt。

把所有的 Factory 和 Factory 有关的实现都删了，不需要。

2024-08-13 08:58 UTC, flycash commented on internal/datasource/internal/statement/type.go
> +type StmtFactory interface {
暂时不要提前设计并实现这个不同 Stmt 的分发机制。

2024-08-13 08:58 UTC, flycash commented on internal/datasource/internal/statement/type.go
> +type StmtFactory interface {
Context 有关的也删了，用不上。

2024-08-13 08:58 UTC, flycash commented on internal/datasource/shardingsource/sharding_datasource.go
> +	facade, err := statement.NewStmtFacade(ctx, s)
这边就是固定调用 statement.Prepare()

2024-08-13 08:58 UTC, flycash commented on internal/datasource/internal/statement/delay_statement.go
> +	key := query.Datasource + "." + query.DB + "." + query.Table
后续会参考 Transaction 的机制，在 baseHandler 里面维持住一个 map[int64]Stmt 的结构，用于分发

2024-08-14 11:52 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +	testCasesQuery := []struct {
这个测试用例需要重新设计，引入 before，在 before 里面返回 DelayStmt 的实例。

测试用例包括：
- before 里面返回没有 key1 的，而后经过测试之后，验证里面已经有一个 key 1 对应的 stmt 了
- before 里面返回有 key1 的，经过测试之后，发现复用了已有的
- key1 存在，但是因为 ds 不同，所以出现了 key2
- key1 存在，但是因为 db 不同，所以出现了 key3
- key1 存在，但是因为 table 不同，所以出现了 key4

2024-08-14 11:52 UTC, flycash commented on internal/datasource/internal/statement/types.go
> +func Prepare(ctx context.Context, f datasource.Finder) (*DelayStmt, error) {
这个文件重命名为 prepare

2024-08-14 11:52 UTC, flycash commented on internal/datasource/internal/errs/error.go
> +var ErrUnsupportedDistributedPrepare = errors.New(" 不支持的分布式预处理类型")
这个错误应该用不上了，你可以删了？

2024-08-15 01:23 UTC, longyue0521 requested changes

2024-08-15 01:23 UTC, longyue0521 commented on internal/datasource/internal/statement/datasource.mock.go
> +package statement
学习使用[uber-go/mock](https://github.com/uber-go/mock),简化mock代码,并将其生成到 internal/statement/mocks 中

1. 定义参考 https://github.com/ecodeclub/webook/blob/dev/internal/question/internal/service/examine.go#L32
2. 使用参考 https://github.com/ecodeclub/webook/blob/dev/internal/question/internal/integration/examine_handler_test.go#L57-#L65

2024-08-15 01:23 UTC, longyue0521 commented on internal/datasource/internal/statement/delay_statement_test.go
> +				return delayStmt
1. 使用go mocks 生成重构
2. 测试代码应该与被测单元的api耦合而不是实现细节

2024-08-15 10:09 UTC, penyz commented on internal/datasource/internal/statement/delay_statement_test.go
> +				return delayStmt
第1点难点在于用gomocks生成datasource的话不具备finder功能，但delayStmt依赖于finder
第2点不是很理解，其实这里的操作算是预处理吧，不算啊是实现细节

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +			assert.Equal(t, len(stmt.stmts), tc.wantStmtsCnt)
这个顺序你反掉了，老外的习惯是 t, expect, actual，也即是预期值在真实值前面

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +			tc.initMockSql()
把这部分合并进去 before 里面

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +type MockDataSourceSuite struct {
改名叫做 DelayStatementTestSuite

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +	datasource.DataSource
mockgen 搞不了你就额外提供一个 mock_datasource_test，然后把 mock 的代码挪过去，不要和 TestSuite 放在一起。

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +	datasource.DataSource
我建议你这里不要用一个 datasource 的字段，你在各个测试用例里面单独创建 datasource，避免测试之间的耦合。

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +	datasource.DataSource
在设计测试的时候有一些原则，其中比较重要的一条就是独立性。
共用一个 mock 对象很容易违背这个问题。比如说有些人的设计是第二个测试依赖于第一个测试的某些条件，这就引起了耦合。所以直接不用这种字段，而是尽量每个测试用例都自己创建 datasource，就没什么问题了。

2024-08-15 11:41 UTC, flycash commented on internal/datasource/internal/statement/delay_statement_test.go
> +				return delayStmt
就这样吧。后续如果引入了 Datasource 和 Finder 的聚合接口，再来用 mockgen

2024-08-17 14:49 UTC, flycash approved these changes

2024-08-17 14:49 UTC, merged